/*
Test generated by RoostGPT for test postman-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

{
  background: null,
  rule: null,
  scenario: 'Delete an existing product\r\n' +
    '    Given there is an existing product with ID 1\r\n' +
    '    When the client sends a DELETE request to "/api/products/1"\r\n' +
    '    Then the response status code should be 200\r\n' +
    '    And the product with ID 1 should no longer exist',
  title: 'Delete an existing product'
}

*/package org.agoncal.application.RoostTest;

import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.junit.Test;

import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.equalTo;

public class DeleteProductTest {

    @Test
    public void testDeleteExistingProduct() {
        // set up the RestAssured target
        RestAssured.baseURI = System.getenv("ROOST_SERVER_URL");
        RestAssured.basePath = "/api/products";

        // send a GET request to endpoint to ensure product with ID 1 exists
        given().
                contentType(ContentType.JSON).
        when().
                get("/1").
        then().
                statusCode(200);

        // send a DELETE request to endpoint to delete product with ID 1
        Response response = given().
                contentType(ContentType.JSON).
        when().
                delete("/1").
        then().
                statusCode(200).
                extract().
                response();

        // the product with ID 1 should no longer exist
        given().
                contentType(ContentType.JSON).
        when().
                get("/1").
        then().
                statusCode(404);
    }
}
