/*
Test generated by RoostGPT for test postman-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

{
  background: null,
  rule: null,
  scenario: 'Get all products\r\n' +
    '    When the client sends a GET request "/api/products" to get the list of all products\r\n' +
    '    Then the list of products returned should be empty',
  title: 'Get all products'
}

*/package org.agoncal.application.RoostTest;

import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.empty;

public class ProductApiTest {

    @BeforeAll
    public static void init() {
        RestAssured.baseURI = System.getenv("ROOST_SERVER_URL");
        RestAssured.basePath = "/api/products";
    }

    // Scenario: Get all products
    // Clearly, as per the API spec, the return array is empty, hence the product list should be empty
    @Test
    public void testGetAllProducts() {
        given()
            .contentType(ContentType.JSON)
        .when()
            .get()
        .then()
            .statusCode(200)
            .body("", empty());
    }
}
