/*
Test generated by RoostGPT for test postman-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

{
  background: null,
  rule: null,
  scenario: 'Get all products\r\n' +
    '    When the client sends a GET request "/api/products" to get the list of all products\r\n' +
    '    Then the list of products returned should be empty',
  title: 'Get all products'
}

*/package org.agoncal.application.RoostTest;

import org.junit.jupiter.api.Test;

import static io.restassured.RestAssured.given;
import static io.restassured.path.json.JsonPath.from;
import static org.hamcrest.CoreMatchers.is;

public class ProductTest {

    private String ROOST_SERVER_URL = System.getenv("ROOST_SERVER_URL");

    @Test
    // Scenario: Test to get all products
    public void testGetAllProducts() {
        given()
            .baseUri(ROOST_SERVER_URL)
            .basePath("/api/products")
        .when()
            .get()
        .then()
            .statusCode(200)
            // Check if the products list is empty
            .body("isEmpty()", is(true))
        ;
    }
}
