/*
Test generated by RoostGPT for test postman-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

{
  background: null,
  rule: null,
  scenario: 'Get all products\r\n' +
    '    When the client sends a GET request "/api/products" to get the list of all products\r\n' +
    '    Then the list of products returned should be empty',
  title: 'Get all products'
}

*/package org.agoncal.application.RoostTest;

import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.is;
import static org.hamcrest.Matchers.empty;
import org.junit.jupiter.api.Test;
import io.restassured.http.ContentType;
import io.restassured.RestAssured;

public class RoostTest {

    // Define the system environment variable
    private static final String ROOST_SERVER_URL = System.getenv("ROOST_SERVER_URL");

    // Configuring the Base URI
    static {
        RestAssured.baseURI = ROOST_SERVER_URL + "/api";
    }

    @Test
    public void getAllProducts_returnsEmptyList() {
        // The expectation of this test is that the product list is empty.

        given()
        .when()
            .get("/products")
        .then()
            .assertThat()
            .statusCode(200)
            // The response should be an empty list as per the API Spec
            .body(is(empty()))
            .contentType(ContentType.JSON);
    }
}
