/*
Test generated by RoostGPT for test agoncal-application-petstore-ee7 using AI Type Open AI and AI Model gpt-4

Test Scenario 1: Positive Test - Equal Objects
- Description: Verify that the equals method correctly identifies two identical Country objects as equal.
- Steps: Create two Country objects with the same isoCode. Call the equals method on the first object, passing in the second object.
- Expected Result: The equals method should return true.

Test Scenario 2: Negative Test - Different Objects
- Description: Verify that the equals method correctly identifies two different Country objects as not equal.
- Steps: Create two Country objects with different isoCodes. Call the equals method on the first object, passing in the second object.
- Expected Result: The equals method should return false.

Test Scenario 3: Negative Test - Null Object
- Description: Verify that the equals method correctly identifies a null object as not equal.
- Steps: Create a Country object. Call the equals method on this object, passing in null.
- Expected Result: The equals method should return false.

Test Scenario 4: Negative Test - Different Class
- Description: Verify that the equals method correctly identifies an object of a different class as not equal.
- Steps: Create a Country object and an object of a different class. Call the equals method on the Country object, passing in the object of a different class.
- Expected Result: The equals method should return false.

Test Scenario 5: Positive Test - Same Object
- Description: Verify that the equals method correctly identifies the same object as equal.
- Steps: Create a Country object. Call the equals method on this object, passing in itself.
- Expected Result: The equals method should return true.

Test Scenario 6: Edge Case - Empty isoCode
- Description: Verify that the equals method correctly handles Country objects with empty isoCodes.
- Steps: Create two Country objects with empty isoCodes. Call the equals method on the first object, passing in the second object.
- Expected Result: The equals method should return true.
*/
package org.agoncal.application.petstore.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

public class Country_equals_f2d574000d_Test {

    private Country country1;
    private Country country2;

    @BeforeEach
    public void setUp() {
        country1 = new Country();
        country2 = new Country();
    }

    @Test
    public void testEqualObjects() {
        country1.setIsoCode("US");
        country2.setIsoCode("US");
        assertTrue(country1.equals(country2));
    }

    @Test
    public void testDifferentObjects() {
        country1.setIsoCode("US");
        country2.setIsoCode("UK");
        assertFalse(country1.equals(country2));
    }

    @Test
    public void testNullObject() {
        country1.setIsoCode("US");
        assertFalse(country1.equals(null));
    }

    @Test
    public void testDifferentClass() {
        country1.setIsoCode("US");
        String notACountry = "Not a country";
        assertFalse(country1.equals(notACountry));
    }

    @Test
    public void testSameObject() {
        country1.setIsoCode("US");
        assertTrue(country1.equals(country1));
    }

    @Test
    public void testEmptyIsoCode() {
        country1.setIsoCode("");
        country2.setIsoCode("");
        assertTrue(country1.equals(country2));
    }
}
